name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ruby-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.0'
          bundler-cache: true

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bundle install

      # Step 4: Run StandardRB
      - name: Run StandardRB
        run: bundle exec standardrb

      # Step 5: Run RSpec tests
      - name: Run RSpec tests
        run: bundle exec rspec
